dependencies {
    // 未来 gateway 实现编译期使用，implementation 不向消费者泄漏编译类路径
    implementation project(':soda-components:soda-component-infrastructure-starter')
    implementation project(':soda-user:soda-user-domain')
    implementation "org.mybatis.spring.boot:mybatis-spring-boot-starter:${mybatisSpringBootVersion}"
    runtimeOnly 'com.mysql:mysql-connector-j'
}
